# Form implementation generated from reading ui file 'tic-tac-toe-dp\gui\xox.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 800)
        MainWindow.setMinimumSize(QtCore.QSize(800, 800))
        MainWindow.setMaximumSize(QtCore.QSize(800, 800))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 800))
        self.centralwidget.setMaximumSize(QtCore.QSize(800, 800))
        self.centralwidget.setStyleSheet("#frame_game {\n"
"background-color: rgb(239, 239, 239);\n"
"border-radius: 20px\n"
"}\n"
"\n"
"QLabel {\n"
"color: rgb(12,16,25);\n"
"font: 16pt \"Arial\";\n"
"text-align: left;\n"
"\n"
"}\n"
"\n"
"\n"
"#frame_nam, #frame_spm, #frame_tmm {\n"
"background-color:rgba(0,0,0,8);\n"
"border-radius: 25px;\n"
"border: 2px solid rgba(0,0,0,24)\n"
"\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedwidget_content = QtWidgets.QStackedWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedwidget_content.sizePolicy().hasHeightForWidth())
        self.stackedwidget_content.setSizePolicy(sizePolicy)
        self.stackedwidget_content.setMinimumSize(QtCore.QSize(800, 800))
        self.stackedwidget_content.setMaximumSize(QtCore.QSize(800, 800))
        self.stackedwidget_content.setStyleSheet("#page_1_menu  {\n"
"    background-color: rgb(248, 249, 249);\n"
"}\n"
"\n"
"#page_2_game {\n"
"background-color: rgb(248, 249, 249);\n"
"}\n"
"\n"
"")
        self.stackedwidget_content.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.stackedwidget_content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.stackedwidget_content.setObjectName("stackedwidget_content")
        self.page_1_menu = QtWidgets.QWidget()
        self.page_1_menu.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.page_1_menu.setStyleSheet("#button_spm {\n"
"background-color: rgb(229, 231, 233)\n"
"}\n"
"\n"
"#button_spm::hover {\n"
"border: 2px solid rgb(20,124,236);\n"
"background-color: rgba(20,124,236, 20);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"border: 2px solid rgb(20,124,236);\n"
"background-color: rgba(20,124,236, 20);\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(12,16,25);\n"
"border: 2px solid  rgb(202, 207, 210);\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QGroupBox {\n"
"color: rgb(12,16,25);\n"
"background-color: rgb(229, 231, 233);\n"
"    font: 700 16pt \"Arial\";\n"
"border:  2px solid rgb(12,16,25);\n"
"border-radius: 25px;\n"
"margin: 10px 0 0 0;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-position: top center; /* Başlığı ortalamak için */\n"
"    subcontrol-origin: margin;\n"
"    \n"
"}")
        self.page_1_menu.setObjectName("page_1_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_1_menu)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.verticalLayout_2.setContentsMargins(10, 20, 10, 10)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.game_header = QtWidgets.QLabel(parent=self.page_1_menu)
        self.game_header.setMinimumSize(QtCore.QSize(0, 80))
        self.game_header.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        self.game_header.setFont(font)
        self.game_header.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.game_header.setStyleSheet("\n"
"color: rgb(12,16,25);\n"
"font: 36pt \"Forte\";\n"
"\n"
"\n"
"")
        self.game_header.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.game_header.setObjectName("game_header")
        self.verticalLayout_2.addWidget(self.game_header, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.game_image = QtWidgets.QLabel(parent=self.page_1_menu)
        self.game_image.setMinimumSize(QtCore.QSize(200, 200))
        self.game_image.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        self.game_image.setFont(font)
        self.game_image.setText("")
        self.game_image.setPixmap(QtGui.QPixmap(":/icons/tic-tac-toe.png"))
        self.game_image.setScaledContents(True)
        self.game_image.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.game_image.setObjectName("game_image")
        self.verticalLayout_2.addWidget(self.game_image, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.button_spm = QtWidgets.QPushButton(parent=self.page_1_menu)
        self.button_spm.setMinimumSize(QtCore.QSize(275, 50))
        self.button_spm.setMaximumSize(QtCore.QSize(275, 50))
        self.button_spm.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button_spm.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.button_spm.setStyleSheet("color: rgb(20,124,236);")
        self.button_spm.setObjectName("button_spm")
        self.verticalLayout_2.addWidget(self.button_spm, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.groupBox = QtWidgets.QGroupBox(parent=self.page_1_menu)
        self.groupBox.setMinimumSize(QtCore.QSize(350, 275))
        self.groupBox.setMaximumSize(QtCore.QSize(350, 275))
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(0, 40, 0, 20)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_mark_selection = QtWidgets.QFrame(parent=self.groupBox)
        self.frame_mark_selection.setMinimumSize(QtCore.QSize(300, 75))
        self.frame_mark_selection.setMaximumSize(QtCore.QSize(300, 75))
        self.frame_mark_selection.setStyleSheet("\n"
"#frame_mark_selection{\n"
"border: 2px solid rgb(215, 219, 221);\n"
"background-color: rgb(215, 219, 221);\n"
"border-radius: 25px; \n"
"}\n"
"\n"
"QLabel{\n"
"font: 14pt \"Arial\";\n"
"color: rgb(12,16,25);\n"
"padding: 0 0 0 5;\n"
"}\n"
"\n"
"QRadioButton {\n"
"width: 48px;\n"
"height: 48px;\n"
"border-radius: 25px;\n"
"border: 1px solid rgb(202, 207, 210);\n"
"}\n"
"\n"
"\n"
"QRadioButton::hover {\n"
"border: 1px solid rgba(20,124,236, 50);\n"
"background-color: rgba(20,124,236, 25)\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"width: 48px; /* İşaret kutusunun genişliği */\n"
"height: 48px; /* İşaret kutusunun yüksekliği */\n"
"border: None;\n"
"}\n"
"")
        self.frame_mark_selection.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_mark_selection.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_mark_selection.setObjectName("frame_mark_selection")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_mark_selection)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.text_mark_selection = QtWidgets.QLabel(parent=self.frame_mark_selection)
        self.text_mark_selection.setStyleSheet("")
        self.text_mark_selection.setObjectName("text_mark_selection")
        self.horizontalLayout_5.addWidget(self.text_mark_selection)
        self.radio_button_x = QtWidgets.QRadioButton(parent=self.frame_mark_selection)
        self.radio_button_x.setMinimumSize(QtCore.QSize(50, 50))
        self.radio_button_x.setMaximumSize(QtCore.QSize(50, 50))
        self.radio_button_x.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.radio_button_x.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.radio_button_x.setStyleSheet("\n"
"QRadioButton::indicator {\n"
"image: url(\":/icons/x.png\");\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"width: 43px;\n"
"height: 43px;\n"
"border: 3px solid rgb(255, 183, 67);\n"
"border-radius: 25px;\n"
"background-color: rgba(255, 183, 67, 50);\n"
"border-radius: 24px;\n"
"image: url(\":/icons/x_crown.png\");\n"
"}")
        self.radio_button_x.setText("")
        self.radio_button_x.setIconSize(QtCore.QSize(10, 10))
        self.radio_button_x.setObjectName("radio_button_x")
        self.horizontalLayout_5.addWidget(self.radio_button_x)
        self.radio_button_o = QtWidgets.QRadioButton(parent=self.frame_mark_selection)
        self.radio_button_o.setMinimumSize(QtCore.QSize(50, 50))
        self.radio_button_o.setMaximumSize(QtCore.QSize(50, 50))
        self.radio_button_o.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.radio_button_o.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.radio_button_o.setStyleSheet("QRadioButton::indicator {\n"
"\n"
"image: url(\":/icons/o.png\");\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"width: 43px;\n"
"height: 43px;\n"
"border: 3px solid rgb(255, 183, 67);\n"
"border-radius: 25px;\n"
"background-color: rgba(255, 183, 67, 50);\n"
"border-radius: 24px;\n"
"image: url(\":/icons/o_crown.png\");\n"
"}")
        self.radio_button_o.setText("")
        self.radio_button_o.setCheckable(True)
        self.radio_button_o.setObjectName("radio_button_o")
        self.horizontalLayout_5.addWidget(self.radio_button_o)
        self.verticalLayout_3.addWidget(self.frame_mark_selection, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.button_easy_mode = QtWidgets.QPushButton(parent=self.groupBox)
        self.button_easy_mode.setMinimumSize(QtCore.QSize(180, 50))
        self.button_easy_mode.setMaximumSize(QtCore.QSize(180, 50))
        self.button_easy_mode.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button_easy_mode.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.button_easy_mode.setStyleSheet("color: rgb(20,124,236);")
        self.button_easy_mode.setObjectName("button_easy_mode")
        self.verticalLayout_3.addWidget(self.button_easy_mode, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.button_hard_mode = QtWidgets.QPushButton(parent=self.groupBox)
        self.button_hard_mode.setMinimumSize(QtCore.QSize(180, 50))
        self.button_hard_mode.setMaximumSize(QtCore.QSize(180, 50))
        self.button_hard_mode.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button_hard_mode.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.button_hard_mode.setStyleSheet("color: rgb(20,124,236);")
        self.button_hard_mode.setObjectName("button_hard_mode")
        self.verticalLayout_3.addWidget(self.button_hard_mode, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_2.addWidget(self.groupBox, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.button_exit = QtWidgets.QPushButton(parent=self.page_1_menu)
        self.button_exit.setMinimumSize(QtCore.QSize(90, 50))
        self.button_exit.setMaximumSize(QtCore.QSize(90, 50))
        self.button_exit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button_exit.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.button_exit.setStyleSheet("#button_exit {\n"
"background-color: rgb(229, 231, 233);\n"
"border: 2px solid rgb(202, 207, 210);\n"
"color: rgb(233,20,76)\n"
"}\n"
"\n"
"#button_exit::hover {\n"
"background-color: rgba(233,20,76, 20);\n"
"border: 2px solid rgb(233,20,76)\n"
"}")
        self.button_exit.setObjectName("button_exit")
        self.verticalLayout_2.addWidget(self.button_exit, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.by_anil_ergan = QtWidgets.QLabel(parent=self.page_1_menu)
        self.by_anil_ergan.setStyleSheet("font: italic 8pt \"Arial\";")
        self.by_anil_ergan.setObjectName("by_anil_ergan")
        self.verticalLayout_2.addWidget(self.by_anil_ergan)
        self.stackedwidget_content.addWidget(self.page_1_menu)
        self.page_2_game = QtWidgets.QWidget()
        self.page_2_game.setStyleSheet("")
        self.page_2_game.setObjectName("page_2_game")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2_game)
        self.verticalLayout_4.setContentsMargins(0, 50, 0, 0)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_game = QtWidgets.QFrame(parent=self.page_2_game)
        self.frame_game.setMinimumSize(QtCore.QSize(600, 600))
        self.frame_game.setMaximumSize(QtCore.QSize(600, 600))
        self.frame_game.setToolTipDuration(0)
        self.frame_game.setStyleSheet("#frame_game * {\n"
"font: italic 18pt \"Arial\";\n"
"color:  rgba(12,16,25, 150)\n"
"\n"
"}\n"
"\n"
"#frame_game {\n"
"background-color: rgb(202, 207, 210);\n"
"\n"
"}\n"
"QFrame {\n"
"background-color: rgb(248, 249, 249);\n"
"\n"
"}\n"
"\n"
"QPushButton {\n"
"background-color: transparent;\n"
"}\n"
"\n"
"#frame_cell_11, #mark_11  {border-top-left-radius: 15px;}\n"
"#frame_cell_13, #mark_13 {border-top-right-radius: 15px;}\n"
"#frame_cell_31, #mark_31  {border-bottom-left-radius: 15px;}\n"
"#frame_cell_33, #mark_33  {border-bottom-right-radius: 15px;}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgba(20,124,236, 20)\n"
"}\n"
"\n"
"QPushButton {\n"
"width: 100px;\n"
"height: 100px;\n"
"\n"
"}\n"
"\n"
"QLabel {background-color:transparent}\n"
"")
        self.frame_game.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_game.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_game.setObjectName("frame_game")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_game)
        self.gridLayout.setContentsMargins(8, 8, 8, 8)
        self.gridLayout.setSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_cell_13 = QtWidgets.QFrame(parent=self.frame_game)
        self.frame_cell_13.setMinimumSize(QtCore.QSize(190, 190))
        self.frame_cell_13.setMaximumSize(QtCore.QSize(190, 190))
        self.frame_cell_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_cell_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_cell_13.setObjectName("frame_cell_13")
        self.mark_13 = QtWidgets.QPushButton(parent=self.frame_cell_13)
        self.mark_13.setGeometry(QtCore.QRect(0, 0, 190, 190))
        self.mark_13.setMinimumSize(QtCore.QSize(190, 190))
        self.mark_13.setMaximumSize(QtCore.QSize(190, 190))
        self.mark_13.setText("")
        self.mark_13.setIconSize(QtCore.QSize(180, 180))
        self.mark_13.setObjectName("mark_13")
        self.value_cell_13 = QtWidgets.QLabel(parent=self.frame_cell_13)
        self.value_cell_13.setGeometry(QtCore.QRect(10, 10, 191, 51))
        self.value_cell_13.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.value_cell_13.setStyleSheet("")
        self.value_cell_13.setText("")
        self.value_cell_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.value_cell_13.setIndent(-1)
        self.value_cell_13.setObjectName("value_cell_13")
        self.gridLayout.addWidget(self.frame_cell_13, 0, 4, 1, 1)
        self.frame_cell_32 = QtWidgets.QFrame(parent=self.frame_game)
        self.frame_cell_32.setMinimumSize(QtCore.QSize(190, 190))
        self.frame_cell_32.setMaximumSize(QtCore.QSize(190, 190))
        self.frame_cell_32.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_cell_32.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_cell_32.setObjectName("frame_cell_32")
        self.mark_32 = QtWidgets.QPushButton(parent=self.frame_cell_32)
        self.mark_32.setGeometry(QtCore.QRect(0, 0, 190, 190))
        self.mark_32.setText("")
        self.mark_32.setIconSize(QtCore.QSize(180, 180))
        self.mark_32.setObjectName("mark_32")
        self.value_cell_32 = QtWidgets.QLabel(parent=self.frame_cell_32)
        self.value_cell_32.setGeometry(QtCore.QRect(10, 10, 191, 51))
        self.value_cell_32.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.value_cell_32.setText("")
        self.value_cell_32.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.value_cell_32.setObjectName("value_cell_32")
        self.gridLayout.addWidget(self.frame_cell_32, 2, 3, 1, 1)
        self.frame_cell_31 = QtWidgets.QFrame(parent=self.frame_game)
        self.frame_cell_31.setMinimumSize(QtCore.QSize(190, 190))
        self.frame_cell_31.setMaximumSize(QtCore.QSize(190, 190))
        self.frame_cell_31.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_cell_31.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_cell_31.setObjectName("frame_cell_31")
        self.mark_31 = QtWidgets.QPushButton(parent=self.frame_cell_31)
        self.mark_31.setGeometry(QtCore.QRect(0, 0, 190, 190))
        self.mark_31.setText("")
        self.mark_31.setIconSize(QtCore.QSize(180, 180))
        self.mark_31.setObjectName("mark_31")
        self.value_cell_31 = QtWidgets.QLabel(parent=self.frame_cell_31)
        self.value_cell_31.setGeometry(QtCore.QRect(10, 10, 191, 51))
        self.value_cell_31.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.value_cell_31.setText("")
        self.value_cell_31.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.value_cell_31.setObjectName("value_cell_31")
        self.gridLayout.addWidget(self.frame_cell_31, 2, 2, 1, 1)
        self.frame_cell_11 = QtWidgets.QFrame(parent=self.frame_game)
        self.frame_cell_11.setMinimumSize(QtCore.QSize(190, 190))
        self.frame_cell_11.setMaximumSize(QtCore.QSize(190, 190))
        self.frame_cell_11.setStyleSheet("")
        self.frame_cell_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_cell_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_cell_11.setObjectName("frame_cell_11")
        self.mark_11 = QtWidgets.QPushButton(parent=self.frame_cell_11)
        self.mark_11.setGeometry(QtCore.QRect(0, 0, 190, 190))
        self.mark_11.setStyleSheet("")
        self.mark_11.setText("")
        self.mark_11.setIconSize(QtCore.QSize(180, 180))
        self.mark_11.setCheckable(False)
        self.mark_11.setChecked(False)
        self.mark_11.setObjectName("mark_11")
        self.value_cell_11 = QtWidgets.QLabel(parent=self.frame_cell_11)
        self.value_cell_11.setGeometry(QtCore.QRect(10, 10, 191, 51))
        self.value_cell_11.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.value_cell_11.setText("")
        self.value_cell_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.value_cell_11.setObjectName("value_cell_11")
        self.gridLayout.addWidget(self.frame_cell_11, 0, 2, 1, 1)
        self.frame_cell_21 = QtWidgets.QFrame(parent=self.frame_game)
        self.frame_cell_21.setMinimumSize(QtCore.QSize(190, 190))
        self.frame_cell_21.setMaximumSize(QtCore.QSize(190, 190))
        self.frame_cell_21.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_cell_21.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_cell_21.setObjectName("frame_cell_21")
        self.mark_21 = QtWidgets.QPushButton(parent=self.frame_cell_21)
        self.mark_21.setGeometry(QtCore.QRect(0, 0, 190, 190))
        self.mark_21.setText("")
        self.mark_21.setIconSize(QtCore.QSize(180, 180))
        self.mark_21.setObjectName("mark_21")
        self.value_cell_21 = QtWidgets.QLabel(parent=self.frame_cell_21)
        self.value_cell_21.setGeometry(QtCore.QRect(10, 10, 191, 51))
        self.value_cell_21.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.value_cell_21.setText("")
        self.value_cell_21.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.value_cell_21.setObjectName("value_cell_21")
        self.gridLayout.addWidget(self.frame_cell_21, 1, 2, 1, 1)
        self.frame_cell_12 = QtWidgets.QFrame(parent=self.frame_game)
        self.frame_cell_12.setMinimumSize(QtCore.QSize(190, 190))
        self.frame_cell_12.setMaximumSize(QtCore.QSize(190, 190))
        self.frame_cell_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_cell_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_cell_12.setObjectName("frame_cell_12")
        self.mark_12 = QtWidgets.QPushButton(parent=self.frame_cell_12)
        self.mark_12.setGeometry(QtCore.QRect(0, 0, 190, 190))
        self.mark_12.setText("")
        self.mark_12.setIconSize(QtCore.QSize(180, 180))
        self.mark_12.setCheckable(False)
        self.mark_12.setChecked(False)
        self.mark_12.setObjectName("mark_12")
        self.value_cell_12 = QtWidgets.QLabel(parent=self.frame_cell_12)
        self.value_cell_12.setGeometry(QtCore.QRect(10, 10, 191, 51))
        self.value_cell_12.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.value_cell_12.setText("")
        self.value_cell_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.value_cell_12.setObjectName("value_cell_12")
        self.gridLayout.addWidget(self.frame_cell_12, 0, 3, 1, 1)
        self.frame_cell_33 = QtWidgets.QFrame(parent=self.frame_game)
        self.frame_cell_33.setMinimumSize(QtCore.QSize(190, 190))
        self.frame_cell_33.setMaximumSize(QtCore.QSize(190, 190))
        self.frame_cell_33.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_cell_33.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_cell_33.setObjectName("frame_cell_33")
        self.mark_33 = QtWidgets.QPushButton(parent=self.frame_cell_33)
        self.mark_33.setGeometry(QtCore.QRect(0, 0, 190, 190))
        self.mark_33.setText("")
        self.mark_33.setIconSize(QtCore.QSize(180, 180))
        self.mark_33.setObjectName("mark_33")
        self.value_cell_33 = QtWidgets.QLabel(parent=self.frame_cell_33)
        self.value_cell_33.setGeometry(QtCore.QRect(10, 10, 191, 51))
        self.value_cell_33.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.value_cell_33.setText("")
        self.value_cell_33.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.value_cell_33.setObjectName("value_cell_33")
        self.gridLayout.addWidget(self.frame_cell_33, 2, 4, 1, 1)
        self.frame_cell_23 = QtWidgets.QFrame(parent=self.frame_game)
        self.frame_cell_23.setMinimumSize(QtCore.QSize(190, 190))
        self.frame_cell_23.setMaximumSize(QtCore.QSize(190, 190))
        self.frame_cell_23.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_cell_23.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_cell_23.setObjectName("frame_cell_23")
        self.mark_23 = QtWidgets.QPushButton(parent=self.frame_cell_23)
        self.mark_23.setGeometry(QtCore.QRect(0, 0, 190, 190))
        self.mark_23.setText("")
        self.mark_23.setIconSize(QtCore.QSize(180, 180))
        self.mark_23.setObjectName("mark_23")
        self.value_cell_23 = QtWidgets.QLabel(parent=self.frame_cell_23)
        self.value_cell_23.setGeometry(QtCore.QRect(10, 10, 191, 51))
        self.value_cell_23.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.value_cell_23.setText("")
        self.value_cell_23.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.value_cell_23.setObjectName("value_cell_23")
        self.gridLayout.addWidget(self.frame_cell_23, 1, 4, 1, 1)
        self.frame_cell_22 = QtWidgets.QFrame(parent=self.frame_game)
        self.frame_cell_22.setMinimumSize(QtCore.QSize(190, 190))
        self.frame_cell_22.setMaximumSize(QtCore.QSize(190, 190))
        self.frame_cell_22.setStyleSheet("")
        self.frame_cell_22.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_cell_22.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_cell_22.setObjectName("frame_cell_22")
        self.mark_22 = QtWidgets.QPushButton(parent=self.frame_cell_22)
        self.mark_22.setGeometry(QtCore.QRect(0, 0, 190, 190))
        self.mark_22.setText("")
        self.mark_22.setIconSize(QtCore.QSize(180, 180))
        self.mark_22.setObjectName("mark_22")
        self.value_cell_22 = QtWidgets.QLabel(parent=self.frame_cell_22)
        self.value_cell_22.setGeometry(QtCore.QRect(10, 10, 191, 51))
        self.value_cell_22.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.value_cell_22.setText("")
        self.value_cell_22.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.value_cell_22.setObjectName("value_cell_22")
        self.gridLayout.addWidget(self.frame_cell_22, 1, 3, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_game, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.frame_menu = QtWidgets.QFrame(parent=self.page_2_game)
        self.frame_menu.setMinimumSize(QtCore.QSize(600, 120))
        self.frame_menu.setMaximumSize(QtCore.QSize(600, 120))
        self.frame_menu.setStyleSheet("#frame_menu {\n"
"background-color: rgb(229, 231, 233);\n"
"border:  none;\n"
"border-top-left-radius: 20px;\n"
"border-top-right-radius: 20px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"border: 2px solid rgb(20,124,236);\n"
"background-color: rgba(20,124,236, 20);\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 16pt \"Arial\";\n"
"border: 2px solid  rgb(202, 207, 210);\n"
"border-radius: 25px;\n"
"color: rgb(20,124,236);\n"
"}\n"
"\n"
"QLabel {\n"
"font: 24pt \"Arial\";\n"
"font: 87 32pt \"Arial Black\";\n"
"color: rgb(250,251,255);\n"
"border-radius: 40px;\n"
"}")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_menu)
        self.horizontalLayout.setContentsMargins(30, 0, 10, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_reset = QtWidgets.QPushButton(parent=self.frame_menu)
        self.button_reset.setMinimumSize(QtCore.QSize(100, 50))
        self.button_reset.setMaximumSize(QtCore.QSize(100, 50))
        self.button_reset.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button_reset.setObjectName("button_reset")
        self.horizontalLayout.addWidget(self.button_reset)
        self.button_menu = QtWidgets.QPushButton(parent=self.frame_menu)
        self.button_menu.setMinimumSize(QtCore.QSize(100, 50))
        self.button_menu.setMaximumSize(QtCore.QSize(100, 50))
        self.button_menu.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button_menu.setObjectName("button_menu")
        self.horizontalLayout.addWidget(self.button_menu)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.frame_announce = QtWidgets.QFrame(parent=self.frame_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_announce.sizePolicy().hasHeightForWidth())
        self.frame_announce.setSizePolicy(sizePolicy)
        self.frame_announce.setMinimumSize(QtCore.QSize(150, 100))
        self.frame_announce.setMaximumSize(QtCore.QSize(150, 100))
        self.frame_announce.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_announce.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_announce.setObjectName("frame_announce")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_announce)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_winner_announce = QtWidgets.QFrame(parent=self.frame_announce)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_winner_announce.sizePolicy().hasHeightForWidth())
        self.frame_winner_announce.setSizePolicy(sizePolicy)
        self.frame_winner_announce.setMinimumSize(QtCore.QSize(100, 50))
        self.frame_winner_announce.setMaximumSize(QtCore.QSize(100, 50))
        self.frame_winner_announce.setStyleSheet("#frame_winner_announce{\n"
"border-radius: 15px;\n"
"}")
        self.frame_winner_announce.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_winner_announce.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_winner_announce.setObjectName("frame_winner_announce")
        self.crown = QtWidgets.QLabel(parent=self.frame_winner_announce)
        self.crown.setGeometry(QtCore.QRect(50, 0, 45, 45))
        self.crown.setMinimumSize(QtCore.QSize(45, 45))
        self.crown.setMaximumSize(QtCore.QSize(45, 45))
        self.crown.setStyleSheet("")
        self.crown.setText("")
        self.crown.setScaledContents(True)
        self.crown.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.crown.setObjectName("crown")
        self.winner_mark = QtWidgets.QLabel(parent=self.frame_winner_announce)
        self.winner_mark.setGeometry(QtCore.QRect(0, 0, 50, 50))
        self.winner_mark.setMinimumSize(QtCore.QSize(50, 50))
        self.winner_mark.setMaximumSize(QtCore.QSize(50, 50))
        self.winner_mark.setStyleSheet("")
        self.winner_mark.setText("")
        self.winner_mark.setScaledContents(True)
        self.winner_mark.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.winner_mark.setObjectName("winner_mark")
        self.draw = QtWidgets.QLabel(parent=self.frame_winner_announce)
        self.draw.setGeometry(QtCore.QRect(0, 0, 100, 50))
        self.draw.setMinimumSize(QtCore.QSize(100, 50))
        self.draw.setMaximumSize(QtCore.QSize(100, 50))
        self.draw.setStyleSheet("#draw{\n"
"color: rgba(255,183,67,255);\n"
"font: 900 24pt \"Arial Black\";\n"
"background-color: transparent;\n"
"}")
        self.draw.setText("")
        self.draw.setScaledContents(True)
        self.draw.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.draw.setObjectName("draw")
        self.verticalLayout_5.addWidget(self.frame_winner_announce, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.horizontalLayout.addWidget(self.frame_announce)
        self.verticalLayout_4.addWidget(self.frame_menu, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.stackedwidget_content.addWidget(self.page_2_game)
        self.verticalLayout.addWidget(self.stackedwidget_content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedwidget_content.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.game_header.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Tic-Tac-Toe</span></p></body></html>"))
        self.button_spm.setText(_translate("MainWindow", "Single Player Mode"))
        self.groupBox.setTitle(_translate("MainWindow", "Play Against Computer"))
        self.text_mark_selection.setText(_translate("MainWindow", "Mark Selection"))
        self.button_easy_mode.setText(_translate("MainWindow", "Easy Mode"))
        self.button_hard_mode.setText(_translate("MainWindow", "Hard Mode"))
        self.button_exit.setText(_translate("MainWindow", "Exit"))
        self.by_anil_ergan.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">by Anıl ERGAN</p></body></html>"))
        self.button_reset.setText(_translate("MainWindow", "Reset"))
        self.button_menu.setText(_translate("MainWindow", "Menu"))
